### ISSUE TITLE
Ausführen des Beispielskripts mithilfe der CLI

### ISSUE THREAD

**Issue by Vuizur** [pyroll-project/pyroll-core#20]
Hallo zusammen. :D

Ich versuche gerade, eine beispielhafte Rechnung mithilfe der CLI auszuführen. Dazu habe ich pyroll in einer virtuellen Umgebung installiert (mit Poetry und dann die `poetry shell` aktiviert). Dann habe ich einen neuen Ordner erstellt und `pyroll new` ausgeführt. Danach habe ich `pyroll input-py solve report` ausgeführt, was mir allerdings folgenden Fehler ausspuckt:

```
(pyroll-gui-py3.10) PS C:\Users\hanne\Documents\Programme\pyroll-gui\pyrolltest> pyroll new
[INFO] pyroll.ui.cli.program: Created config file in: C:\Users\hanne\Documents\Programme\pyroll-gui\pyrolltest\config.yaml
[INFO] pyroll.ui.cli.program: Created input file in: C:\Users\hanne\Documents\Programme\pyroll-gui\pyrolltest\input.py
(pyroll-gui-py3.10) PS C:\Users\hanne\Documents\Programme\pyroll-gui\pyrolltest> pyroll input-py solve report
>>
[INFO] pyroll.ui.cli.program: Loaded plugins: ['pyroll.freiberg_flow_stress', 'pyroll.hensel_power_and_labour', 'pyroll.integral_thermal', 'pyroll.lendl_equivalent_method', 'pyroll.wusatowski_spreading', 'pyroll.zouhar_contact', 'pyroll.gui'].
[INFO] pyroll.ui.cli.program: Reading input from: C:\Users\hanne\Documents\Programme\pyroll-gui\pyrolltest\input.py
[INFO] pyroll.ui.cli.program: Finished reading input.
[INFO] pyroll.ui.cli.program: Starting solution process...
[INFO] pyroll.core.roll_pass.roll_pass: Started solving of RollPass 'Oval I'.
C:\Users\hanne\Documents\Programme\pyroll-gui\.venv\lib\site-packages\pyroll\core\plugin_host.py:160: ShapelyDeprecationWarning: The array interface is deprecated and will no longer work in Shapely 2.0. Convert the '.coords' to a numpy array instead.
  return self.get_from_hook(key)
Traceback (most recent call last):
  File "C:\Users\hanne\Documents\Programme\pyroll-gui\.venv\lib\site-packages\pyroll\core\solve.py", line 11, in solve
    last_profile = u.solve(last_profile)
  File "C:\Users\hanne\Documents\Programme\pyroll-gui\.venv\lib\site-packages\pyroll\core\unit.py", line 71, in solve
    current_values = self.get_root_hook_results()
  File "C:\Users\hanne\Documents\Programme\pyroll-gui\.venv\lib\site-packages\pyroll\core\roll_pass\roll_pass.py", line 89, in get_root_hook_results
    super_results = super().get_root_hook_results()
  File "C:\Users\hanne\Documents\Programme\pyroll-gui\.venv\lib\site-packages\pyroll\core\unit.py", line 48, in get_root_hook_results
    out_profile_results = self.out_profile.get_root_hook_results()
  File "C:\Users\hanne\Documents\Programme\pyroll-gui\.venv\lib\site-packages\pyroll\core\plugin_host.py", line 168, in get_root_hook_results 
    result = self.get_from_hook(key)
  File "C:\Users\hanne\Documents\Programme\pyroll-gui\.venv\lib\site-packages\pyroll\core\plugin_host.py", line 136, in get_from_hook
    result = hook(**self.hook_args)
  File "C:\Users\hanne\Documents\Programme\pyroll-gui\.venv\lib\site-packages\pluggy\_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "C:\Users\hanne\Documents\Programme\pyroll-gui\.venv\lib\site-packages\pluggy\_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\hanne\Documents\Programme\pyroll-gui\.venv\lib\site-packages\pluggy\_callers.py", line 60, in _multicall
    return outcome.get_result()
  File "C:\Users\hanne\Documents\Programme\pyroll-gui\.venv\lib\site-packages\pluggy\_result.py", line 60, in get_result
    raise ex[1].with_traceback(ex[2])
  File "C:\Users\hanne\Documents\Programme\pyroll-gui\.venv\lib\site-packages\pluggy\_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\hanne\Documents\Programme\pyroll-gui\.venv\lib\site-packages\pyroll\integral_thermal\roll_pass_impls.py", line 27, in temperature
    return roll_pass.in_profile.temperature + roll_pass.temperature_change
  File "C:\Users\hanne\Documents\Programme\pyroll-gui\.venv\lib\site-packages\pyroll\core\plugin_host.py", line 160, in __getattr__
    return self.get_from_hook(key)
  File "C:\Users\hanne\Documents\Programme\pyroll-gui\.venv\lib\site-packages\pyroll\core\plugin_host.py", line 136, in get_from_hook
    result = hook(**self.hook_args)
  File "C:\Users\hanne\Documents\Programme\pyroll-gui\.venv\lib\site-packages\pluggy\_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "C:\Users\hanne\Documents\Programme\pyroll-gui\.venv\lib\site-packages\pluggy\_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\hanne\Documents\Programme\pyroll-gui\.venv\lib\site-packages\pluggy\_callers.py", line 60, in _multicall
    return outcome.get_result()
  File "C:\Users\hanne\Documents\Programme\pyroll-gui\.venv\lib\site-packages\pluggy\_result.py", line 60, in get_result
    raise ex[1].with_traceback(ex[2])
  File "C:\Users\hanne\Documents\Programme\pyroll-gui\.venv\lib\site-packages\pluggy\_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\hanne\Documents\Programme\pyroll-gui\.venv\lib\site-packages\pyroll\integral_thermal\roll_pass_impls.py", line 76, in temperature_change
    return roll_pass.temperature_change_by_contact + roll_pass.temperature_change_by_deformation
  File "C:\Users\hanne\Documents\Programme\pyroll-gui\.venv\lib\site-packages\pyroll\core\plugin_host.py", line 160, in __getattr__
    return self.get_from_hook(key)
  File "C:\Users\hanne\Documents\Programme\pyroll-gui\.venv\lib\site-packages\pyroll\core\plugin_host.py", line 136, in get_from_hook
    result = hook(**self.hook_args)
  File "C:\Users\hanne\Documents\Programme\pyroll-gui\.venv\lib\site-packages\pluggy\_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "C:\Users\hanne\Documents\Programme\pyroll-gui\.venv\lib\site-packages\pluggy\_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\hanne\Documents\Programme\pyroll-gui\.venv\lib\site-packages\pluggy\_callers.py", line 60, in _multicall
    return outcome.get_result()
  File "C:\Users\hanne\Documents\Programme\pyroll-gui\.venv\lib\site-packages\pluggy\_result.py", line 60, in get_result
    raise ex[1].with_traceback(ex[2])
  File "C:\Users\hanne\Documents\Programme\pyroll-gui\.venv\lib\site-packages\pluggy\_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\hanne\Documents\Programme\pyroll-gui\.venv\lib\site-packages\pyroll\integral_thermal\roll_pass_impls.py", line 48, in temperature_change_by_contact
    mean_density(roll_pass)
  File "C:\Users\hanne\Documents\Programme\pyroll-gui\.venv\lib\site-packages\pyroll\integral_thermal\helper.py", line 9, in mean_density     
    return (unit.in_profile.density + unit.out_profile.density) / 2
  File "C:\Users\hanne\Documents\Programme\pyroll-gui\.venv\lib\site-packages\pyroll\core\plugin_host.py", line 160, in __getattr__
    return self.get_from_hook(key)
  File "C:\Users\hanne\Documents\Programme\pyroll-gui\.venv\lib\site-packages\pyroll\core\plugin_host.py", line 136, in get_from_hook
    result = hook(**self.hook_args)
  File "C:\Users\hanne\Documents\Programme\pyroll-gui\.venv\lib\site-packages\pluggy\_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "C:\Users\hanne\Documents\Programme\pyroll-gui\.venv\lib\site-packages\pluggy\_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\hanne\Documents\Programme\pyroll-gui\.venv\lib\site-packages\pluggy\_callers.py", line 60, in _multicall
    return outcome.get_result()
  File "C:\Users\hanne\Documents\Programme\pyroll-gui\.venv\lib\site-packages\pluggy\_result.py", line 60, in get_result
    raise ex[1].with_traceback(ex[2])
  File "C:\Users\hanne\Documents\Programme\pyroll-gui\.venv\lib\site-packages\pluggy\_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\hanne\Documents\Programme\pyroll-gui\.venv\lib\site-packages\pyroll\integral_thermal\profile_impls.py", line 8, in density   
    raise ValueError("You must provide a density to use the pyroll-integral-thermal plugin.")
ValueError: You must provide a density to use the pyroll-integral-thermal plugin.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\hanne\Documents\Programme\pyroll-gui\.venv\Scripts\pyroll.exe\__main__.py", line 7, in <module>
  File "C:\Users\hanne\Documents\Programme\pyroll-gui\.venv\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\hanne\Documents\Programme\pyroll-gui\.venv\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\hanne\Documents\Programme\pyroll-gui\.venv\lib\site-packages\click\core.py", line 1688, in invoke
    rv.append(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\hanne\Documents\Programme\pyroll-gui\.venv\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\hanne\Documents\Programme\pyroll-gui\.venv\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\hanne\Documents\Programme\pyroll-gui\.venv\lib\site-packages\click\decorators.py", line 38, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "C:\Users\hanne\Documents\Programme\pyroll-gui\.venv\lib\site-packages\pyroll\ui\cli\program.py", line 129, in solve
    pyroll.core.solve(state.sequence, state.in_profile)
  File "C:\Users\hanne\Documents\Programme\pyroll-gui\.venv\lib\site-packages\pyroll\core\solve.py", line 13, in solve
    raise RuntimeError(f"Solution of pass sequence failed at unit {u}.") from e
RuntimeError: Solution of pass sequence failed at unit RollPass 'Oval I'.
```

Betriebssystem: Windows 10 
Python-Version: 3.10

**Comment by axtimhaus** [comment]
Da du das Plugin für die thermische Rechnung lädst, musst du auf dem `in_profile` auch `density` und `thermal_capacity` übergeben. Das ist in der Beispieleingabe nicht drinne.

**Comment by Vuizur** [comment]
Super, danke dir. Nach dem Auskommentieren des thermischen Modells funktioniert es.
